<?php
require_once __DIR__ . '/config.php';
$uuid=isset($_REQUEST['id'])?trim((string)$_REQUEST['id']):'';
if(!preg_match('/^[A-Za-z0-9-]{16,64}$/',$uuid)){http_response_code(422);exit('Cliente inválido.');}
$safe=mysqli_real_escape_string($link,$uuid);$message='';$ok=false;
if($_SERVER['REQUEST_METHOD']==='POST'){
 $days=filter_input(INPUT_POST,'dias_corte',FILTER_VALIDATE_INT,array('options'=>array('min_range'=>0,'max_range'=>90)));
 if($days===false){$message='Informe um número entre 0 e 90.';}else{$ok=(bool)@mysqli_query($link,"UPDATE sis_cliente SET dias_corte=".(int)$days." WHERE uuid_cliente='{$safe}' LIMIT 1");$message=$ok?'Dias de corte atualizados com sucesso.':'Não foi possível atualizar os dias de corte.';}
}
$q=@mysqli_query($link,"SELECT nome,dias_corte FROM sis_cliente WHERE uuid_cliente='{$safe}' LIMIT 1");$client=$q?mysqli_fetch_assoc($q):null;if(!$client){http_response_code(404);exit('Cliente não encontrado.');}
?><!doctype html><html><head><meta charset="utf-8"><style>body{font:14px Arial,sans-serif;color:#17324b;background:#f3f7fb;margin:0;padding:24px}.box{max-width:560px;margin:auto;background:#fff;border:1px solid #d8e3ee;border-radius:12px;padding:22px}.warning{padding:13px 15px;background:#fff8e1;border:1px solid #efd47b;border-radius:8px;color:#705300;line-height:1.45}.field{margin:18px 0}label{display:block;font-weight:700;margin-bottom:7px}input{width:140px;padding:10px;border:1px solid #b9cadb;border-radius:7px}button{padding:10px 15px;border:0;border-radius:7px;background:#1769d2;color:#fff;font-weight:700;cursor:pointer}.msg{margin:0 0 14px;padding:10px;border-radius:7px;background:<?= $ok?'#e9f8ef':'#fff0f0' ?>}</style></head><body><div class="box"><h2><?= htmlspecialchars($client['nome'],ENT_QUOTES,'UTF-8') ?></h2><?php if($message!==''){?><div class="msg"><?= htmlspecialchars($message,ENT_QUOTES,'UTF-8') ?></div><?php }?><div class="warning"><strong>Atenção</strong><br>Não altere os dias de corte deste cliente sem autorização do administrador.</div><form method="post" onsubmit="return confirm('Confirma a alteração dos dias de corte deste cliente?');"><input type="hidden" name="id" value="<?= htmlspecialchars($uuid,ENT_QUOTES,'UTF-8') ?>"><div class="field"><label for="dias_corte">Dias após o vencimento para corte</label><input id="dias_corte" name="dias_corte" type="number" min="0" max="90" required value="<?= (int)$client['dias_corte'] ?>"></div><button type="submit">Salvar alteração</button></form></div><?php if($ok){?><script>parent.postMessage({type:'mka-content-modal-refresh'},'*');</script><?php }?></body></html>
