<?php
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
require_once __DIR__ . '/config.php';
if (empty($_SESSION['mka_logado']) && empty($_SESSION['MKA_Usuario']) && empty($_SESSION['MM_Usuario'])) { http_response_code(401); exit('Sessão expirada.'); }
$login = isset($_GET['login']) ? trim((string) $_GET['login']) : '';
if ($login === '' || strlen($login) > 128) { http_response_code(422); exit('Cliente inválido.'); }
$safe = mysqli_real_escape_string($link, $login);
$result = @mysqli_query($link, "SELECT framedipaddress,acctstarttime,acctstoptime,callingstationid,nasipaddress FROM radacct WHERE username='{$safe}' ORDER BY acctstarttime DESC LIMIT 10");
?><!doctype html><html><head><meta charset="utf-8"><style>body{font:14px Arial,sans-serif;color:#16324a;background:#f3f7fb;margin:0;padding:22px}h2{margin:0 0 16px}.table-wrap{overflow:auto;background:#fff;border:1px solid #d8e3ee;border-radius:10px}table{border-collapse:collapse;width:100%;min-width:720px}th,td{padding:11px 12px;border-bottom:1px solid #e5edf5;text-align:left}th{background:#1e67c6;color:#fff}tr:last-child td{border-bottom:0}.online{color:#16834d;font-weight:700}.empty{text-align:center;color:#65788b;padding:28px}</style></head><body><h2>Últimas 10 conexões/reconexões</h2><div class="table-wrap"><table><thead><tr><th>#</th><th>Início</th><th>Fim</th><th>IP</th><th>MAC/CPE</th><th>Concentrador</th></tr></thead><tbody><?php $i=0;if($result)while($row=mysqli_fetch_assoc($result)){$i++;$online=empty($row['acctstoptime'])||$row['acctstoptime']==='0000-00-00 00:00:00';?><tr><td><?= $i ?></td><td><?= htmlspecialchars($row['acctstarttime'],ENT_QUOTES,'UTF-8') ?></td><td class="<?= $online?'online':'' ?>"><?= $online?'Online agora':htmlspecialchars($row['acctstoptime'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($row['framedipaddress']?:'-',ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($row['callingstationid']?:'-',ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($row['nasipaddress']?:'-',ENT_QUOTES,'UTF-8') ?></td></tr><?php }if(!$i){?><tr><td class="empty" colspan="6">Nenhuma conexão encontrada para este cliente.</td></tr><?php }?></tbody></table></div></body></html>
